### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by slavakurilyak** [spences10/sveltekit-graphcms-starter-blog#3]
![500 Server Error](https://user-images.githubusercontent.com/6625584/121841606-82b39c80-cc93-11eb-9cdf-1127158a26d2.jpeg)

**Comment by spences10** [comment]
I think I may have deleted the project for this, this is if you're referring to the demo link @slavakurilyak 

If you spin up your own project it'll be fine

**Comment by slavakurilyak** [comment]
@spences10 Thanks for letting me know. If you delete the demo link, then the confusion will be resolved.

**Comment by spences10** [comment]
I've reinstated the project, the demo link should work fine now @slavakurilyak 

Thanks 👍
